### ISSUE TITLE
Typedoc-plugin-pages supports

### ISSUE THREAD

**Issue by yboujraf** [krisztianb/typedoc-umlclass#10]
Dear @krisztianb 

I am using [typedoc-plugin-pages](https://github.com/mipatterson/typedoc-plugin-pages#readme) and yours plugin.

It will be nice if i can combine both plugins.

Best regards,
Youssef

**Comment by krisztianb** [comment]
Why is this not possible? Do you receive an error message when running TypeDoc?

**Comment by yboujraf** [comment]
Dear @krisztianb

Not tested becasue I don't know if I could use more than one plugin at time in the settings and how to do that

### Settings

plugin: 'typedoc-umlclass',

Best Regards
youssef

**Comment by krisztianb** [comment]
Well, then try it. :smile:

As far as I know typedoc loads each plugin it detects. So you don't have to configure this yourself. But it's best to ask this on Gitter or the typedoc Issues page I guess.

**Comment by krisztianb** [comment]
I've just tried this myself and it works as expected. All the plugins that are installed are detected and loaded automatically:

> Loaded plugin C:\MyProjects\code\class-proj\node_modules\typedoc-plantuml
> Loaded plugin C:\MyProjects\code\class-proj\node_modules\typedoc-umlclass
> 
> Using TypeScript 3.8.3 from C:\MyProjects\code\class-proj\node_modules\typescript\lib
> Rendering [========================================] 100%
