### ISSUE TITLE
Typedoc keeps hanging and generates a lot of logs

### ISSUE THREAD

**Issue by SimonCockx** [krisztianb/typedoc-umlclass#12]
When I run typedoc with this plugin enabled, the console hangs at `Documentation generated at ...` and doesn't continue. The only thing that happens is that it keeps generating log-files `hs_err_pidxxxx.log` with a trace starting with `There is insufficient memory for the Java Runtime Environment to continue.` Also log files called `replay_pid1000.log`. I'm guessing this plugin consumes too much memory.

Console output:
```
> typedoc --umlClassDiagramType detailed --excludePrivate --tsconfig src/tsconfig.app.json --mode modules -module commonjs --exclude **/*.spec.ts --out documentation/typedoc src/app && documentation\serve-typedoc

Loaded plugin C:\Users\Werk\Desktop\beerhive\venuewebsite\node_modules\typedoc-umlclass

Using TypeScript 3.8.3 from C:\Users\Werk\Desktop\beerhive\venuewebsite\node_modules\typescript\lib
Rendering [========================================] 100%

Documentation generated at C:\Users\Werk\Desktop\beerhive\venuewebsite\documentation\typedoc
```
[hs_err_pid1000.log](https://github.com/krisztianb/typedoc-umlclass/files/4682809/hs_err_pid1000.log)
[replay_pid1000.log](https://github.com/krisztianb/typedoc-umlclass/files/4682810/replay_pid1000.log)

**Comment by krisztianb** [comment]
Yes, there is definitely a memory and CPU usage issue. It depends on how many diagrams are generated. However I've not had this log issue you are experiencing.

The main problem is that I'm using the node-plantuml module which spawn a separate JAVA process for each diagram that is generated.

Actually I want to replace that module as I think it is too complicated and no longer maintained. I hope we can solve this issue with another module: https://github.com/agirorn/plantuml/issues/2

Also related to: https://github.com/krisztianb/typedoc-umlclass/issues/4

**Comment by krisztianb** [comment]
Can you tell me where those log files are generated?

**Comment by SimonCockx** [comment]
They were generated in the current directory of the terminal.

**Comment by krisztianb** [comment]
Closing this. Solution is going to be the same as for #4
