### ISSUE TITLE
SVG image is not displayed on the page

### ISSUE THREAD

**Issue by yboujraf** [krisztianb/typedoc-umlclass#2]
Dear @krisztianb 

# SVG - umlClassDiagramFormat: 'svg',

## Picture
I have an issue, the picture is not displayed on the page

![image](https://user-images.githubusercontent.com/6151258/81496436-f24ca080-92b7-11ea-96e6-099e2fac4e1c.png)

When clicking on the link, I have this :

![image](https://user-images.githubusercontent.com/6151258/81496458-0ee8d880-92b8-11ea-8663-ce49a4ee49f6.png)

The html file :

[alldestinationsassociationnamesrequestmessagecommand.zip](https://github.com/krisztianb/typedoc-umlclass/files/4605470/alldestinationsassociationnamesrequestmessagecommand.zip)

But the picture is complete

[umlClassDiagram-7.zip](https://github.com/krisztianb/typedoc-umlclass/files/4605477/umlClassDiagram-7.zip)

Best Regards,
Youssef

**Comment by krisztianb** [comment]
That's very odd. The svg file actually contains 2 graphics which is obviously an invalid svg file. It contains the normal svg and another svg that encapsulates a png image. Will have to take a closer look...

**Comment by krisztianb** [comment]
I had some time to investigate this issue. Turn out this is a bug in the the [node-plantuml](https://github.com/markushedvall/node-plantuml) module. I'm going to open an issue on their page.

The typedoc-plantuml plugin uses version 0.4.4 which is fine.

As I tend to update to the latest versions of dependencies I used 0.9.0 in which SVG output is broken. I'm going to revert to version 0.5.0 which I've just tested and works fine.

**Comment by krisztianb** [comment]
Closing this as it is going to be fixed in the next version.

**Comment by yboujraf** [comment]
Dear @krisztianb 

I confirm it is fixed and is displayed when setting contains :

```
umlClassDiagramLocation: 'embed',
umlClassDiagramFormat: 'svg',
```

**Comment by krisztianb** [comment]
@yboujraf thanks for the confirmation. It should also work with `umlClassDiagramLocation: 'local'`
