### ISSUE TITLE
TypeDoc 0.24.x support

### ISSUE THREAD

**Issue by Maximvdw** [krisztianb/typedoc-umlclass#31]
The plugin does not seem to support typedoc 0.24.x and gives the error:
" Tried to set an option (umlClassDiagram) that was not declared"

0.23.x works perfectly fine

**Comment by krisztianb** [comment]
To me it sounds like the plugin is not loaded and therefore TypeDoc doesn't like the option passed to it.

**Update:** confirmed on https://github.com/TypeStrong/typedoc/releases/tag/v0.24.0

> TypeDoc will no longer automatically load plugins from node_modules. Specify the --plugin option to indicate which modules should be loaded.

To fix this add the parameter `--plugin typedoc-umlclass` to the command that calls TypeDoc.

Nevertheless I should update the plugin to get rid of the peer dependency warning displayed by NPM when updating TypeDoc to 0.24.

**Comment by krisztianb** [comment]
Peer dependency warning fixed in new version **0.7.1**. Enjoy. 🥳
