### ISSUE TITLE
Format functions in diagrams

### ISSUE THREAD

**Issue by denis-migdal** [krisztianb/typedoc-umlclass#34]
Hi,

I started to use this extension. However, I noticed that the generated graphs are quite hard to read due to the lack of formatting.

Could it be possible to add some formatting, e.g. putting functions and argument names in bold, putting the return value in italic/red, or whatever, to improve the graphs readability ?

It seems possible as I saw that plantUML allows some formatting :
https://plantuml.com/en/creole

Cordially,

**Comment by krisztianb** [comment]
Hi. Thanks for your input. This seems like a good idea and should work.

* Basic Creole syntax for formatting: https://plantuml.com/en/creole
* Legacy HTML syntax for coloring: https://plantuml.com/creole#f42f1366d9ab93bb

We could add these to the following things:

* class/interface
  * name
  * template parameters
* property
  * name
  * type
* method
  * name
  * parameter names
  * parameter types
  * return type
  * template parameters

Now I just need to find the time to do this. :thinking:

**Comment by krisztianb** [comment]
I don't know if you are still needing this, but it is now released as part of version **0.9.0** 
Feedback is very much appreciated. Happy testing. 🎉
