### ISSUE TITLE
Add support for TypeDoc 0.27.x

### ISSUE THREAD

**Issue by claremacrae** [krisztianb/typedoc-umlclass#37]
Many thanks for this project.

In [this version](https://github.com/obsidian-tasks-group/obsidian-tasks/tree/add-typedoc-umlclass) of a Common JS project, I get 'The plugin typedoc-umlclass could not be loaded', `typedoc-umlclass` fails to load giving this output:

```
[error] The plugin typedoc-umlclass could not be loaded
[error] Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/clare/Documents/develop/Obsidian/schemar/obsidian-tasks/node_modules/typedoc/dist/index.js from /Users/clare/Documents/develop/Obsidian/schemar/obsidian-tasks/node_modules/typedoc-umlclass/dist/plugin.js not supported.
Instead change the require of index.js in /Users/clare/Documents/develop/Obsidian/schemar/obsidian-tasks/node_modules/typedoc-umlclass/dist/plugin.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/clare/Documents/develop/Obsidian/schemar/obsidian-tasks/node_modules/typedoc-umlclass/dist/plugin.js:42:19)
[error] Found 2 errors and 0 warnings
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Steps to reproduce:

```bash
git clone https://github.com/obsidian-tasks-group/obsidian-tasks.git
cd ./obsidian-tasks
git checkout add-typedoc-umlclass
yarn
yarn code-docs
```

I presume this is the usual 'Common JS' projects cannot use 'ESM' code...

Or is there any way to configure typedoc-umlclass to be used in CommonJS projects, please?

**Comment by krisztianb** [comment]
Hello. It looks like that you are using TypeDoc 0.27 which has dropped support for non-ESM plugins: https://github.com/TypeStrong/typedoc/releases/tag/v0.27.0

I will have to convert this plugin to ESM in order for it to work with the TypeDoc version you are using. This should not be too difficult unless there are other changes in TypeDoc that break the plugin. I should have time to look into this next week.

**Comment by claremacrae** [comment]
Hi, thank you.

Let me try using TypeDoc 0.26 and see if that works, and let you know...

**Comment by claremacrae** [comment]
> Hello. It looks like that you are using TypeDoc 0.27 which has dropped support for non-ESM plugins: https://github.com/TypeStrong/typedoc/releases/tag/v0.27.0

Yes, switching to TypeDoc 0.26.11 enables UML diagrams to be created for many/most of my classes - thank you!

> I will have to convert this plugin to ESM in order for it to work with the TypeDoc version you are using. This should not be too difficult unless there are other changes in TypeDoc that break the plugin. I should have time to look into this next week.

That's very generous of you, but please don't do it on my account...

I think there's a reasonable chance that my project will be converting to Bun and to ESM at some point, so sticking with a slightly older version of TypeDoc is fine for the time-being.

**Comment by krisztianb** [comment]
New version released: **0.10.1**

Plugin has been updated to work with TypeDoc 0.27.x 🎉

**Comment by claremacrae** [comment]
Can confirm it works - thank you very much!

**Comment by claremacrae** [comment]
> In [this version](https://github.com/obsidian-tasks-group/obsidian-tasks/tree/add-typedoc-umlclass) of a Common JS project, I get 'The plugin typedoc-umlclass could not be loaded', `typedoc-umlclass` fails to load giving this output:


Just to note, I will delete the branch that showed the reproduction now...
