### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by yboujraf** [krisztianb/typedoc-umlclass#4]
Dear @krisztianb 

Which mode is the best to renderize the class diagram ?

# mode setting

## mode: 'file'

The render is fast.

## mode: 'modules'

It takes long time and CPU 100% for rendering the class diagram.

Best Regards,
Youssef

**Comment by krisztianb** [comment]
Good question. Maybe it would be better to ask this question on Gitter to see what really the difference is.

My only guess would be that with mode modules more pages are generated and my regex to check if the page is a detail page is suboptimal/slow.

May I ask how many files (classes etc.) are parsed by typedoc in your project?

**Comment by yboujraf** [comment]
Dear @krisztianb

Around 80 classes in my lib and 400 files(small)

Best Regards,
Youssef

**Comment by krisztianb** [comment]
Can you measure the performance difference with and without the plugin?

**Comment by yboujraf** [comment]
Dear @krisztianb

Will do it tomorrow. Just to know how I could measure the performance when running my npm script ?

Best Regards,
Youssef

**Comment by krisztianb** [comment]
Well, you could use a timer on your phone. 😄  I'm just curious if there is a big difference.

I think with mode module every file is treated as a separate module (which it is). So there are probably more files generated. Therefore the PageEnd event is triggered more often and if my regex is slow that could slow down the whole typedoc process.

If your project is like a library then mode file is probably better suited.

**Comment by yboujraf** [comment]
Dear @krisztianb

# mode setting : file

- without plugin : 11 seconds
- with your plugin : 41 seconds

# mode setting : modules

- without plugin : 14 seconds
- with your plugin : 2 minutes and 51 seconds

Best Regards
Youssef

**Comment by krisztianb** [comment]
Thanks for the data. :+1: 

I have some ideas to speed up the whole process (like caching the PlantUML for classes). I'm sure we can improve this a lot.

**Comment by krisztianb** [comment]
I added some tweaks where I could. I'll wait for Gerrit's reply on Gitter to see if my assumption about detail page detection is correct. Then I could release a new version with the performance tweaks.

I ran some tests locally. What really seems to be the slow thing is the writing of the local image files. So we might not benefit from the changes as much as we want to. 🙄

**Comment by krisztianb** [comment]
Version 0.1.2 is up on NPM with some performance tweaks. If you have time I would be interested if the doc generation is any faster for you now.

**Comment by yboujraf** [comment]
Dear @krisztianb 

# plugin version

With "typedoc-umlclass": "^0.1.2",

# nbr files managed

The src folder has 202 files.

# mode setting : files

without plugin : 11 seconds
with your plugin : 46 seconds


# mode setting : modules

without plugin : 14 seconds
with your plugin : 3 minutes and 40 seconds

Best Regards

**Comment by krisztianb** [comment]
It actually got slower? Holy moly... I don't know what to say. 😕

**Comment by krisztianb** [comment]
Well, I don't want to remove the caching because it actually makes a lot of sense. But I could add a new option to the plugin so that it can be enabled/disabled.

**Comment by krisztianb** [comment]
I have one more idea. [node-plantuml](https://github.com/markushedvall/node-plantuml/) has a feature called NailGun.

> If your application will be making multiple PlantUML requests, it might be a good idea to enable the usage of Nailgun.

It looks like something worth trying to improve performance.

**Comment by krisztianb** [comment]
Unfortunately the NailGun feature of node-plantuml is not working. If that project is discontinued it might be a good idea to switch to another plantuml image generation module like this one: https://github.com/agirorn/plantuml

Or maybe write one myself when I have the time. It looks like it's not that complicated to achieve.

**Comment by yboujraf** [comment]
Dear @krisztianb 

The performance is better than ever on both settings as "files" or "modules"

Best Regards,
Youssef

**Comment by krisztianb** [comment]
Dear @yboujraf glad to hear that alltough I don't really see why this is the case. The plugin still starts a separate JAVA process for every diagram which is unfortunately too much for some systems. I'm still working on a solution for this.

**Comment by krisztianb** [comment]
I have good news here. I created another project called [plantuml-pipe](https://github.com/krisztianb/plantuml-pipe) which is hopefully going to be released on NPM very soon. When that happens I'm going to drop node-plantuml from this plugin and use that project instead.

Current tests indicate that there is a speed gain by about 20% with less CPU and memory consumption.

**Comment by krisztianb** [comment]
Finally fixed this in 0.2.0 🎉 

I'd recommend using the new option `umlClassDiagramGeneratorProcessCount` with the number of your CPUs as the option value.
