### ISSUE TITLE
UML CODE

### ISSUE THREAD

**Issue by yboujraf** [krisztianb/typedoc-umlclass#5]
Dear @krisztianb 

# UML CODE

Could you generate into a seperate file the uml code compatible plantuml ;-) and better if it is in a markdown file.

Best Regards,
Youssef

**Comment by krisztianb** [comment]
What do you exactly mean by markdown file?

My idea is to generate one file per reflection in the images folder just where the diagram images are saved. The file would be named like the image file but with a different extension (eg. CommandBase-umlClassDiagram-415.puml). The file would contain the PlantUML lines of code that were used to generate the diagram.

**Comment by yboujraf** [comment]
Better if you could generate a markdown ans add the plantuml script inside then we could render the class diagram easily.

**Comment by krisztianb** [comment]
Can you give an example please? How would such a markdown file look like? What would be in it besides the PlantUML code?

**Comment by yboujraf** [comment]
Dear @krisztianb 

Two ways possibles (add settings)

### Link

- Add in the asset folder the picture in PNG or SVG
- Add the title of the Class in H1
- Add the link of the picture to display it

### plantuml script

- Add the title of the Class in H1
- Add the script of the plantuml

```
.. uml::

      @startuml
      
      'style options 
      skinparam monochrome true
      skinparam circledCharacterRadius 0
      skinparam circledCharacterFontSize 0
      skinparam classAttributeIconSize 0
      hide empty members
      
      Class01 <|-- Class02
      Class03 *-- Class04
      Class05 o-- Class06
      Class07 .. Class08
      Class09 -- Class10
      
      @enduml
```

Best Regards,
Youssef

**Comment by krisztianb** [comment]
Added in 0.1.6 🎉

**Comment by yboujraf** [comment]
Dear @krisztianb 

I confirm it is done and available on the assets folder with puml extension and could be opened from :

```
http://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000
```

Best Regards,
Youssef

**Comment by krisztianb** [comment]
Dear @yboujraf thanks for the confirmation.
