### ISSUE TITLE
Legend definition if using icon instead of text

### ISSUE THREAD

**Issue by yboujraf** [krisztianb/typedoc-umlclass#7]
Dear @krisztianb 

# Legend

May I ask you to include the legend into the class diagram like ?

![image](https://user-images.githubusercontent.com/6151258/81541909-24bbd380-9374-11ea-8aa4-cf0cd904550b.png)

That means for each icon to have his type or his definition

Best Regards,
Youssef

**Comment by krisztianb** [comment]
Do you mean to include a legend in every diagram image that is generated? Something like this: https://stackoverflow.com/questions/30999290/how-to-generate-a-legend-with-colors-in-plantuml

**Comment by yboujraf** [comment]
Yes it is or specify if an interface, classe,.... like typedoc legend

**Comment by krisztianb** [comment]
What do you mean by 'specify if an interface, classe,....'?

**Comment by yboujraf** [comment]
Dear @krisztianb 

Sorry,

Misunderstanding from me.

For example when using the markdown plugin, we have a folder for each type (class, interface, enum, ...) the idea was the same but in your case, you suggested to have one file per class and logic.

best regards,
Youssef

**Comment by yboujraf** [comment]
Like this

![image](https://user-images.githubusercontent.com/6151258/82767420-b709b000-9e27-11ea-853a-18351c65d174.png)

Best Regards,
Youssef

**Comment by krisztianb** [comment]
I have another idea. Since the legend feature of PlantUML seems to be pretty rudimentary we could add the legend below the image in the HTML instead.

**Comment by krisztianb** [comment]
Added in 0.1.7 🎉
