### ISSUE TITLE
Extend option umlClassDiagramLocation to embed images in the HTML

### ISSUE THREAD

**Issue by krisztianb** [krisztianb/typedoc-umlclass#8]
Add a new option `embed` to the said option which creates a base64 encoded `src` attribute value containing the image. See: https://stackoverflow.com/a/8499716/

**Comment by yboujraf** [comment]
Dear @krisztianb 

Is it activated ?

In the doc, it isn't updated.

Best Regards,
Youssef

**Comment by krisztianb** [comment]
@yboujraf it's not yet available. This is a feature request.

**Comment by krisztianb** [comment]
Added in 0.1.5 🎉
