### ISSUE TITLE
Class Name instead of umlClassDiagram-xxx.png or .svg

### ISSUE THREAD

**Issue by yboujraf** [krisztianb/typedoc-umlclass#9]
Dear @krisztianb 

Is it possible to rename in the \assts\images folder, the plantuml image renderized by the class name instead of umlClassDiagram-xxx.png ?

Best Regards,
Youssef

**Comment by krisztianb** [comment]
Yes, it should be possible to include the class name too. I used a simple counter to ensure unique filenames, because there could be several classes with the same name.

**Comment by krisztianb** [comment]
Closing this as it is going to be part of the next version.

**Comment by yboujraf** [comment]
Dear @krisztianb 

I confirm it is done.

Best Regards,
Youssef
